application: hyperlocative
version: 1
runtime: python
api_version: 1

handlers:
 
  
- url: /static
  static_dir: static
  
- url: /geosearch/static
  static_dir: geosearch/static

- url: /geosearch/.*
  static_files: geosearch/index.html
  upload: geosearch/index.html

- url: /jasperspace/static
  static_dir: jasperspace/static

- url: /jasperspace/.*
  static_files: jasperspace/index.html
  upload: jasperspace/index.html

- url: /issue/.*
  static_files: issue/index.html
  upload: issue/index.html

- url: /issue/javascript
  static_dir: issue/javascript
  mime_type: application/x-javascript
  
- url: /issue/stylesheets
  static_dir: issue/stylesheets
  mime_type: text/css

- url: /issue/images
  static_dir: issue/images
    
- url: /photoset/static
  static_dir: photoset/static

- url: /photoset/.*
  static_files: photoset/index.html
  upload: photoset/index.html
  
- url: /audioboo/static
  static_dir: audioboo/static

- url: /audioboo/.*
  static_files: audioboo/index.html
  upload: audioboo/index.html
  
- url: /iphone-app/static
  static_dir: iphone-app/static

- url: /iphone-app/.*
  static_files: iphone-app/index.html
  upload: iphone-app/index.html
  
- url: .*
  static_files: voluptuousity/index.html
  upload: voluptuousity/index.html 